baseURL = "https://xSteep.github.io/my-cv/"
languageCode = "en-us"
title = "Мое резюме"
theme = "hugo-resume"

[params]
  name = "Федосеев Максим"
  title = "Разработчик ПО"
  email = "ivan@example.com"
  phone = "+7 123 456 78 90"
  address = "Йошкар-Ола, Россия"